### ISSUE TITLE
404 Resource Not Found

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-Connected-Drive#26]
Started to get this error sicne yesterday:

`   Connected Drive Warning         BMW Connected Drive Account: get_account error: Client error '404 Resource Not Found' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles'
For more information check: https://httpstatuses.com/404`

**Comment by ryanbuckner** [comment]
I'm getting a lot of these errors too.   And a lot of errors that I've reached my API  limit.  Currently set at 15 min intervals.

**Comment by FlyingDiver** [comment]
Try upgrading the library:

```
pip3 install --upgrade bimmer_connected
```

**Comment by paddo42** [comment]
I still have the same error after an upgrade to bimmer_connected 0.13.8. 

Someone has posted a similar (?same) issue starting around the same time on the main bimmer_connected GitHub (#544) eventually fixed with the upgraded library, though that person also had bimmer_connected installed incorrectly 

I'm no good at this - can you tell me how to check where indigo is looking for bimmer_connected? Mine is installed inside /opt/homebrew/lib/python3.11/site-packages - is that where it should be? This error for me coincided with a new Mac/Indigo install so I'm not sure if I inadvertently installed bimmer_connected in the wrong place...? Sorry for the stupid questions, and thanks for the plugin, I love it

**Comment by FlyingDiver** [comment]
That is the wrong location.  You need to install it using the pip3.10 command from the Python install that came with Indigo.  Having homebrew on the Indigo server machine is known to cause issues due to conflicting Python installs.

**Comment by paddo42** [comment]
Thanks! I've upgraded to bimmer_connected 0.13.8 at the correct install location for Indigo's Python and it works again. Thanks also for the advice about running Homebrew on an Indigo Server. Homebrew was to install Scrypted to make some local cameras available to Homekit. Currently everything seems to be working, but I'll look to a different Scrypted install method... Thanks again

**Comment by turribeach** [comment]
Confirmed for me too, upgrading bimmer_connected 0.13.8 solves the problem. Closing issue.
